// Package gorm implements the GORM ORM migration diff generator. The canonical
// db/models structs are ORM-neutral (no gorm tags), so this generator parses
// them back into ModelDefinitions and synthesizes ephemeral gorm-tagged mirror
// structs for the Atlas provider. The persisted model stays neutral; the gorm
// view exists only inside the temporary diff module.
package gorm

import (
	"context"
	"embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/polagonow/pola/internal/generators/migration/diff"
	"github.com/polagonow/pola/internal/generators/model/schema"
)

//go:embed all:_templates
var templates embed.FS

var diffTmpl = template.Must(
	template.New("gorm_diff_main.go.tmpl").Delims("[[", "]]").ParseFS(templates, "_templates/gorm_diff_main.go.tmpl"),
)

// GormDiffGenerator generates migrations by diffing gorm-tagged mirror structs
// synthesized from the neutral canonical models.
type GormDiffGenerator struct{}

func (g *GormDiffGenerator) Name() string { return "gorm" }

func (g *GormDiffGenerator) Diff(ctx context.Context, cfg diff.Config) error {
	modelsDir := filepath.Join(cfg.ProjectDir, cfg.ModelsDir)
	defs, err := schema.ParseModelsDir(modelsDir)
	if err != nil {
		return fmt.Errorf("parse models in %s: %w", modelsDir, err)
	}
	if len(defs) == 0 {
		return fmt.Errorf("no models found in %s", modelsDir)
	}

	// Deterministic model order.
	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	// Synthesize gorm-tagged mirror structs.
	imports := map[string]bool{}
	var structs strings.Builder
	for _, name := range names {
		src, imps := mirrorStruct(defs[name])
		structs.WriteString(src)
		structs.WriteString("\n")
		for imp := range imps {
			imports[imp] = true
		}
	}

	tmpDir, err := os.MkdirTemp("", "pola-gorm-diff-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// models_gen.go holds the synthesized gorm mirror structs.
	if err := os.WriteFile(filepath.Join(tmpDir, "models_gen.go"), []byte(renderModelsGen(imports, structs.String())), 0o644); err != nil {
		return fmt.Errorf("write models_gen.go: %w", err)
	}

	// Generate main.go from template.
	data := struct {
		ModulePath   string
		ModelsDir    string
		DriverImport string
		AtlasDialect string
		Models       []string
	}{
		ModulePath:   cfg.ModulePath,
		ModelsDir:    cfg.ModelsDir,
		DriverImport: diff.DriverImportForAdapter(cfg.Adapter),
		AtlasDialect: diff.AtlasDialectForAdapter(cfg.Adapter),
		Models:       names,
	}

	var buf strings.Builder
	if err := diffTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute gorm diff template: %w", err)
	}

	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}

	// Write go.mod with replace directive pointing to the user's project.
	if err := diff.WriteGoMod(tmpDir, "pola-gorm-diff", cfg); err != nil {
		return err
	}

	// Run go mod tidy to resolve dependencies.
	tidy := exec.CommandContext(ctx, "go", "mod", "tidy")
	tidy.Dir = tmpDir
	if out, err := tidy.CombinedOutput(); err != nil {
		return fmt.Errorf("go mod tidy: %s\n%w", out, err)
	}

	// Run the temporary program: args: migrationsDir, migrationName
	run := exec.CommandContext(ctx, "go", "run", ".", cfg.MigrationsDir, cfg.Name)
	run.Dir = tmpDir
	run.Stdout = os.Stdout
	run.Stderr = os.Stderr
	if err := run.Run(); err != nil {
		return fmt.Errorf("gorm migration diff: %w", err)
	}

	return nil
}

// renderModelsGen assembles the models_gen.go source: package clause, the
// collected stdlib imports, and the synthesized structs.
func renderModelsGen(imports map[string]bool, structs string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pola migration diff; DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	if len(imports) > 0 {
		imps := make([]string, 0, len(imports))
		for i := range imports {
			imps = append(imps, i)
		}
		sort.Strings(imps)
		b.WriteString("import (\n")
		for _, i := range imps {
			b.WriteString("\t" + i + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(structs)
	return b.String()
}

// mirrorStruct renders a gorm-tagged struct that reproduces def's table, plus
// the stdlib imports it needs. uuid fields are represented as varchar(36)
// strings and json as json.RawMessage so the mirror needs no external deps.
func mirrorStruct(def *schema.ModelDefinition) (string, map[string]bool) {
	imports := map[string]bool{}
	var b strings.Builder

	fmt.Fprintf(&b, "type %s struct {\n", def.Name)
	if def.HasUUIDPrimaryKey() {
		b.WriteString("\tID string `gorm:\"primaryKey;type:varchar(36)\"`\n")
	} else {
		b.WriteString("\tID uint `gorm:\"primaryKey\"`\n")
	}

	for _, f := range def.Fields {
		if f.Type == schema.FieldReferences {
			goType := "uint"
			if f.RefIDType == schema.FieldUUID {
				goType = "string"
			}
			fmt.Fprintf(&b, "\t%sID %s%s\n", schema.PascalCase(f.Name), goType, gormFKTag(f))
			if f.Polymorphic {
				fmt.Fprintf(&b, "\t%sType string\n", schema.PascalCase(f.Name))
			}
			continue
		}
		fmt.Fprintf(&b, "\t%s %s%s\n", schema.PascalCase(f.Name), mirrorGoType(f, imports), gormScalarTag(f))
	}

	if def.HasTimestamps {
		imports[`"time"`] = true
		b.WriteString("\tCreatedAt time.Time\n\tUpdatedAt time.Time\n")
	}
	if def.SoftDeletes {
		imports[`"time"`] = true
		b.WriteString("\tDeletedAt *time.Time\n")
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "\nfunc (%s) TableName() string { return %q }\n", def.Name, schema.SnakeCase(schema.Pluralize(def.Name)))
	return b.String(), imports
}

// mirrorGoType returns the Go type used in the mirror struct. uuid → varchar(36)
// string and json → json.RawMessage keep the mirror free of external deps.
func mirrorGoType(f schema.Field, imports map[string]bool) string {
	switch {
	case f.Type == schema.FieldUUID, f.Type == schema.FieldString, f.Type == schema.FieldText, schema.ValidatorFieldTypes[f.Type]:
		return "string"
	case f.Type == schema.FieldInt:
		return "int"
	case f.Type == schema.FieldInt64:
		return "int64"
	case f.Type == schema.FieldFloat:
		return "float64"
	case f.Type == schema.FieldBool:
		return "bool"
	case f.Type == schema.FieldTime:
		imports[`"time"`] = true
		return "time.Time"
	case f.Type == schema.FieldBytes:
		return "[]byte"
	case f.Type == schema.FieldJSON:
		imports[`"encoding/json"`] = true
		return "json.RawMessage"
	default:
		return "string"
	}
}

// gormScalarTag reproduces the column type/sizing/index tags for a scalar field,
// matching the DDL the previous per-ORM gorm model generator produced.
func gormScalarTag(f schema.Field) string {
	var parts []string
	switch {
	case f.Type == schema.FieldUUID:
		parts = append(parts, "type:varchar(36)")
	case f.Type == schema.FieldString || schema.ValidatorFieldTypes[f.Type]:
		if f.Limit > 0 {
			parts = append(parts, fmt.Sprintf("type:varchar(%d)", f.Limit))
		} else {
			parts = append(parts, "type:varchar(255)")
		}
	case f.Type == schema.FieldText:
		parts = append(parts, "type:text")
	case f.Type == schema.FieldBytes:
		if f.Limit > 0 {
			parts = append(parts, fmt.Sprintf("size:%d", f.Limit))
		}
	}
	if f.Index {
		parts = append(parts, "index")
	}
	if f.Unique {
		parts = append(parts, "uniqueIndex")
	}
	if len(parts) == 0 {
		return ""
	}
	return " `gorm:\"" + strings.Join(parts, ";") + "\"`"
}

// gormFKTag renders index/unique tags for a foreign-key column.
func gormFKTag(f schema.Field) string {
	var parts []string
	if f.Index {
		parts = append(parts, "index")
	}
	if f.Unique {
		parts = append(parts, "uniqueIndex")
	}
	if len(parts) == 0 {
		return ""
	}
	return " `gorm:\"" + strings.Join(parts, ";") + "\"`"
}
