version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goimports:
      local-prefixes: gojsx
    revive:
      rules:
        - name: comment-spacings
        - name: exported
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - lll
          - revive
        path: _test\.go
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: gojsx
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
