// Package routes implements the route discovery and init overlay autoload.
package routes

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/polagonow/pola/internal/autoload"
)

type autoloadImpl struct{}

func init() {
	autoload.Register(&autoloadImpl{})
}

func (a *autoloadImpl) Name() string { return "routes" }
func (a *autoloadImpl) Priority() int { return 200 }

func (a *autoloadImpl) Contribute(ctx *autoload.Context) error {
	if ctx.ModPath == "" {
		return nil
	}

	routePkgs := discoverRoutePackages(ctx.ProjectDir, ctx.ModPath)
	ctx.Discovery.RoutePkgs = routePkgs

	for i, rp := range routePkgs {
		dep := discoverRouteServiceDep(rp.AbsDir, ctx.ModPath)
		src := generateRouteInit(rp.PkgName, ctx.Opts.PolaPackage, ctx.ModPath, dep)
		initPath := filepath.Join(ctx.TmpDir, fmt.Sprintf("pola_route_init_%d.go", i))
		if err := os.WriteFile(initPath, src, 0o644); err != nil {
			return fmt.Errorf("write route init for %s: %w", rp.PkgName, err)
		}
		ctx.Replace[filepath.Join(rp.AbsDir, "pola_route_init.go")] = initPath
	}

	return nil
}

// discoverRoutePackages walks the routes/ directory and returns metadata
// for every sub-package that contains at least one .go file.
func discoverRoutePackages(projectDir, modPath string) []autoload.RoutePackageInfo {
	routesDir := filepath.Join(projectDir, "routes")
	info, err := os.Stat(routesDir)
	if err != nil || !info.IsDir() {
		return nil
	}

	var pkgs []autoload.RoutePackageInfo
	filepath.WalkDir(routesDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() {
			return nil
		}
		entries, err := os.ReadDir(path)
		if err != nil {
			return nil
		}
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
				rel, _ := filepath.Rel(projectDir, path)
				absDir, _ := filepath.Abs(path)
				pkgs = append(pkgs, autoload.RoutePackageInfo{
					ImportPath: modPath + "/" + filepath.ToSlash(rel),
					AbsDir:     absDir,
					PkgName:    filepath.Base(path),
				})
				break
			}
		}
		return nil
	})

	sort.Slice(pkgs, func(i, j int) bool {
		return pkgs[i].ImportPath < pkgs[j].ImportPath
	})
	return pkgs
}

// generateRouteInit returns the source for a pola_route_init.go file that
// registers a route factory via init().
func generateRouteInit(pkgName, polaPackage, modPath string, dep *autoload.RouteServiceDep) []byte {
	if dep == nil {
		return []byte(fmt.Sprintf(
			"// Code generated by pola; DO NOT EDIT.\npackage %s\n\nimport (\n\t\"%s/core\"\n\t\"%s/routes\"\n)\n\nfunc init() {\n\troutes.Register(func(_ *core.Registry) any { return &Route{} })\n}\n",
			pkgName, polaPackage, polaPackage,
		))
	}

	imports := []string{
		fmt.Sprintf("\t%q", polaPackage+"/core"),
		fmt.Sprintf("\t%q", polaPackage+"/routes"),
	}
	var body string
	var args []string

	if dep.ServicePkg != "" {
		imports = append(imports, fmt.Sprintf("\t%q", dep.ServicePath))
		body += fmt.Sprintf("\t\tsvc := core.MustInvoke[*%s.%s](r)\n", dep.ServicePkg, dep.ServiceType)
		args = append(args, "svc")
	}
	if dep.HasStorage {
		imports = append(imports, fmt.Sprintf("\t%q", polaPackage+"/storage"))
		body += "\t\tstore := core.MustInvoke[storage.Storage](r)\n"
		args = append(args, "store")
	}
	if dep.BlobRepo != "" && modPath != "" {
		imports = append(imports, fmt.Sprintf("\t%q", modPath+"/repositories"))
		body += fmt.Sprintf("\t\tblobs := core.MustInvoke[repositories.%s](r)\n", dep.BlobRepo)
		args = append(args, "blobs")
	}

	return []byte(fmt.Sprintf(
		"// Code generated by pola; DO NOT EDIT.\npackage %s\n\nimport (\n%s\n)\n\nfunc init() {\n\troutes.Register(func(r *core.Registry) any {\n%s\t\treturn NewRoute(%s)\n\t})\n}\n",
		pkgName, strings.Join(imports, "\n"), body, strings.Join(args, ", "),
	))
}

// discoverRouteServiceDep scans a route package for a Route struct with a field
// whose type matches *services.*Service, and returns the dependency info.
func discoverRouteServiceDep(routeDir, modPath string) *autoload.RouteServiceDep {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(routeDir)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasPrefix(entry.Name(), "pola_") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(routeDir, entry.Name()), nil, 0)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != "Route" {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok || st.Fields == nil {
					continue
				}
				dep := &autoload.RouteServiceDep{}
				for _, field := range st.Fields.List {
					switch t := field.Type.(type) {
					case *ast.StarExpr:
						sel, ok := t.X.(*ast.SelectorExpr)
						if !ok {
							continue
						}
						ident, ok := sel.X.(*ast.Ident)
						if !ok {
							continue
						}
						typeName := sel.Sel.Name
						if strings.HasSuffix(typeName, "Service") && dep.ServicePkg == "" {
							dep.ServicePkg = ident.Name
							dep.ServiceType = typeName
							dep.ServicePath = modPath + "/" + ident.Name
						}
					case *ast.SelectorExpr:
						ident, ok := t.X.(*ast.Ident)
						if !ok {
							continue
						}
						typeName := t.Sel.Name
						if ident.Name == "storage" && typeName == "Storage" {
							dep.HasStorage = true
						} else if ident.Name == "repositories" && strings.HasSuffix(typeName, "Repository") {
							dep.BlobRepo = typeName
						}
					}
				}
				if dep.ServicePkg != "" || dep.HasStorage || dep.BlobRepo != "" {
					return dep
				}
			}
		}
	}
	return nil
}
