package codegen

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"
)

// GenerateTS produces the generated.d.ts TypeScript declaration source.
func GenerateTS(result *ParseResult) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by pola; DO NOT EDIT.\n\n")

	// Emit TS interfaces for all referenced named struct types.
	emitted := map[string]bool{}
	if err := emitNamedTypes(&buf, result.NamedTypes, emitted); err != nil {
		return nil, err
	}

	// Build the PolaActions interface with all methods and vars.
	buf.WriteString("interface PolaActions {\n")

	for _, action := range result.Actions {
		for _, m := range action.Methods {
			// JSDoc comment
			buf.WriteString(fmt.Sprintf("  /** %s.%s */\n", action.StructName, m.GoName))

			// Method signature
			params := make([]string, len(m.Params))
			for i, p := range m.Params {
				params[i] = fmt.Sprintf("%s: %s", p.Name, p.TSType)
			}

			returnType := "void"
			if m.HasReturn {
				returnType = m.ReturnTS
			}

			buf.WriteString(fmt.Sprintf("  %s(%s): Promise<%s>;\n", m.JSName, strings.Join(params, ", "), returnType))
		}

		// Vars — we can't know the types at parse time since Vars() returns map[string]any,
		// so we type them as unknown. Users can override with manual .d.ts if needed.
		if action.HasVars {
			buf.WriteString(fmt.Sprintf("  // Variables from %s.Vars()\n", action.StructName))
			buf.WriteString("  readonly [key: string]: unknown;\n")
		}
	}

	buf.WriteString("}\n\n")

	// Module declaration so `import di from "@pola/di"` picks up these types.
	buf.WriteString("declare module \"@pola/di\" {\n")
	buf.WriteString("  const di: PolaActions;\n")
	buf.WriteString("  export default di;\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func emitNamedTypes(buf *bytes.Buffer, namedTypes map[string]*types.Struct, emitted map[string]bool) error {
	// Keep emitting until all types (including transitively discovered ones) are done.
	for {
		progress := false
		for name, st := range namedTypes {
			if emitted[name] {
				continue
			}
			emitted[name] = true
			progress = true

			buf.WriteString(fmt.Sprintf("export interface %s {\n", name))
			fields := StructToTSFields(st, namedTypes)
			for _, f := range fields {
				buf.WriteString(f + "\n")
			}
			buf.WriteString("}\n\n")
		}
		if !progress {
			break
		}
	}
	return nil
}
