// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/polagonow/pola/repository/ent/enttest/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/polagonow/pola/repository/ent/enttest/ent/session"
	"github.com/polagonow/pola/repository/ent/enttest/ent/typedwidget"
	"github.com/polagonow/pola/repository/ent/enttest/ent/widget"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// TypedWidget is the client for interacting with the TypedWidget builders.
	TypedWidget *TypedWidgetClient
	// Widget is the client for interacting with the Widget builders.
	Widget *WidgetClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Session = NewSessionClient(c.config)
	c.TypedWidget = NewTypedWidgetClient(c.config)
	c.Widget = NewWidgetClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Session:     NewSessionClient(cfg),
		TypedWidget: NewTypedWidgetClient(cfg),
		Widget:      NewWidgetClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Session:     NewSessionClient(cfg),
		TypedWidget: NewTypedWidgetClient(cfg),
		Widget:      NewWidgetClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Session.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Session.Use(hooks...)
	c.TypedWidget.Use(hooks...)
	c.Widget.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Session.Intercept(interceptors...)
	c.TypedWidget.Intercept(interceptors...)
	c.Widget.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *TypedWidgetMutation:
		return c.TypedWidget.mutate(ctx, m)
	case *WidgetMutation:
		return c.Widget.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id string) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id string) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id string) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id string) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// TypedWidgetClient is a client for the TypedWidget schema.
type TypedWidgetClient struct {
	config
}

// NewTypedWidgetClient returns a client for the TypedWidget from the given config.
func NewTypedWidgetClient(c config) *TypedWidgetClient {
	return &TypedWidgetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `typedwidget.Hooks(f(g(h())))`.
func (c *TypedWidgetClient) Use(hooks ...Hook) {
	c.hooks.TypedWidget = append(c.hooks.TypedWidget, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `typedwidget.Intercept(f(g(h())))`.
func (c *TypedWidgetClient) Intercept(interceptors ...Interceptor) {
	c.inters.TypedWidget = append(c.inters.TypedWidget, interceptors...)
}

// Create returns a builder for creating a TypedWidget entity.
func (c *TypedWidgetClient) Create() *TypedWidgetCreate {
	mutation := newTypedWidgetMutation(c.config, OpCreate)
	return &TypedWidgetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TypedWidget entities.
func (c *TypedWidgetClient) CreateBulk(builders ...*TypedWidgetCreate) *TypedWidgetCreateBulk {
	return &TypedWidgetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TypedWidgetClient) MapCreateBulk(slice any, setFunc func(*TypedWidgetCreate, int)) *TypedWidgetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TypedWidgetCreateBulk{err: fmt.Errorf("calling to TypedWidgetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TypedWidgetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TypedWidgetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TypedWidget.
func (c *TypedWidgetClient) Update() *TypedWidgetUpdate {
	mutation := newTypedWidgetMutation(c.config, OpUpdate)
	return &TypedWidgetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TypedWidgetClient) UpdateOne(_m *TypedWidget) *TypedWidgetUpdateOne {
	mutation := newTypedWidgetMutation(c.config, OpUpdateOne, withTypedWidget(_m))
	return &TypedWidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TypedWidgetClient) UpdateOneID(id int) *TypedWidgetUpdateOne {
	mutation := newTypedWidgetMutation(c.config, OpUpdateOne, withTypedWidgetID(id))
	return &TypedWidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TypedWidget.
func (c *TypedWidgetClient) Delete() *TypedWidgetDelete {
	mutation := newTypedWidgetMutation(c.config, OpDelete)
	return &TypedWidgetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TypedWidgetClient) DeleteOne(_m *TypedWidget) *TypedWidgetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TypedWidgetClient) DeleteOneID(id int) *TypedWidgetDeleteOne {
	builder := c.Delete().Where(typedwidget.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TypedWidgetDeleteOne{builder}
}

// Query returns a query builder for TypedWidget.
func (c *TypedWidgetClient) Query() *TypedWidgetQuery {
	return &TypedWidgetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTypedWidget},
		inters: c.Interceptors(),
	}
}

// Get returns a TypedWidget entity by its id.
func (c *TypedWidgetClient) Get(ctx context.Context, id int) (*TypedWidget, error) {
	return c.Query().Where(typedwidget.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TypedWidgetClient) GetX(ctx context.Context, id int) *TypedWidget {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TypedWidgetClient) Hooks() []Hook {
	return c.hooks.TypedWidget
}

// Interceptors returns the client interceptors.
func (c *TypedWidgetClient) Interceptors() []Interceptor {
	return c.inters.TypedWidget
}

func (c *TypedWidgetClient) mutate(ctx context.Context, m *TypedWidgetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TypedWidgetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TypedWidgetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TypedWidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TypedWidgetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TypedWidget mutation op: %q", m.Op())
	}
}

// WidgetClient is a client for the Widget schema.
type WidgetClient struct {
	config
}

// NewWidgetClient returns a client for the Widget from the given config.
func NewWidgetClient(c config) *WidgetClient {
	return &WidgetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `widget.Hooks(f(g(h())))`.
func (c *WidgetClient) Use(hooks ...Hook) {
	c.hooks.Widget = append(c.hooks.Widget, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `widget.Intercept(f(g(h())))`.
func (c *WidgetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Widget = append(c.inters.Widget, interceptors...)
}

// Create returns a builder for creating a Widget entity.
func (c *WidgetClient) Create() *WidgetCreate {
	mutation := newWidgetMutation(c.config, OpCreate)
	return &WidgetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Widget entities.
func (c *WidgetClient) CreateBulk(builders ...*WidgetCreate) *WidgetCreateBulk {
	return &WidgetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WidgetClient) MapCreateBulk(slice any, setFunc func(*WidgetCreate, int)) *WidgetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WidgetCreateBulk{err: fmt.Errorf("calling to WidgetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WidgetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WidgetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Widget.
func (c *WidgetClient) Update() *WidgetUpdate {
	mutation := newWidgetMutation(c.config, OpUpdate)
	return &WidgetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WidgetClient) UpdateOne(_m *Widget) *WidgetUpdateOne {
	mutation := newWidgetMutation(c.config, OpUpdateOne, withWidget(_m))
	return &WidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WidgetClient) UpdateOneID(id int) *WidgetUpdateOne {
	mutation := newWidgetMutation(c.config, OpUpdateOne, withWidgetID(id))
	return &WidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Widget.
func (c *WidgetClient) Delete() *WidgetDelete {
	mutation := newWidgetMutation(c.config, OpDelete)
	return &WidgetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WidgetClient) DeleteOne(_m *Widget) *WidgetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WidgetClient) DeleteOneID(id int) *WidgetDeleteOne {
	builder := c.Delete().Where(widget.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WidgetDeleteOne{builder}
}

// Query returns a query builder for Widget.
func (c *WidgetClient) Query() *WidgetQuery {
	return &WidgetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWidget},
		inters: c.Interceptors(),
	}
}

// Get returns a Widget entity by its id.
func (c *WidgetClient) Get(ctx context.Context, id int) (*Widget, error) {
	return c.Query().Where(widget.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WidgetClient) GetX(ctx context.Context, id int) *Widget {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WidgetClient) Hooks() []Hook {
	return c.hooks.Widget
}

// Interceptors returns the client interceptors.
func (c *WidgetClient) Interceptors() []Interceptor {
	return c.inters.Widget
}

func (c *WidgetClient) mutate(ctx context.Context, m *WidgetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WidgetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WidgetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WidgetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WidgetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Widget mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Session, TypedWidget, Widget []ent.Hook
	}
	inters struct {
		Session, TypedWidget, Widget []ent.Interceptor
	}
)
