// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/polagonow/pola/repository/ent/enttest/ent/session"
	"github.com/polagonow/pola/repository/ent/enttest/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() string)
}
