// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polagonow/pola/repository/ent/enttest/ent/predicate"
	"github.com/polagonow/pola/repository/ent/enttest/ent/typedwidget"
)

// TypedWidgetUpdate is the builder for updating TypedWidget entities.
type TypedWidgetUpdate struct {
	config
	hooks    []Hook
	mutation *TypedWidgetMutation
}

// Where appends a list predicates to the TypedWidgetUpdate builder.
func (_u *TypedWidgetUpdate) Where(ps ...predicate.TypedWidget) *TypedWidgetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TypedWidgetUpdate) SetTitle(v string) *TypedWidgetUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TypedWidgetUpdate) SetNillableTitle(v *string) *TypedWidgetUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *TypedWidgetUpdate) SetCount(v int) *TypedWidgetUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *TypedWidgetUpdate) SetNillableCount(v *int) *TypedWidgetUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *TypedWidgetUpdate) AddCount(v int) *TypedWidgetUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *TypedWidgetUpdate) SetRate(v float64) *TypedWidgetUpdate {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *TypedWidgetUpdate) SetNillableRate(v *float64) *TypedWidgetUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *TypedWidgetUpdate) AddRate(v float64) *TypedWidgetUpdate {
	_u.mutation.AddRate(v)
	return _u
}

// SetDone sets the "done" field.
func (_u *TypedWidgetUpdate) SetDone(v bool) *TypedWidgetUpdate {
	_u.mutation.SetDone(v)
	return _u
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (_u *TypedWidgetUpdate) SetNillableDone(v *bool) *TypedWidgetUpdate {
	if v != nil {
		_u.SetDone(*v)
	}
	return _u
}

// Mutation returns the TypedWidgetMutation object of the builder.
func (_u *TypedWidgetUpdate) Mutation() *TypedWidgetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TypedWidgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TypedWidgetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TypedWidgetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TypedWidgetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TypedWidgetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(typedwidget.Table, typedwidget.Columns, sqlgraph.NewFieldSpec(typedwidget.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(typedwidget.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(typedwidget.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(typedwidget.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(typedwidget.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(typedwidget.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Done(); ok {
		_spec.SetField(typedwidget.FieldDone, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{typedwidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TypedWidgetUpdateOne is the builder for updating a single TypedWidget entity.
type TypedWidgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TypedWidgetMutation
}

// SetTitle sets the "title" field.
func (_u *TypedWidgetUpdateOne) SetTitle(v string) *TypedWidgetUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TypedWidgetUpdateOne) SetNillableTitle(v *string) *TypedWidgetUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *TypedWidgetUpdateOne) SetCount(v int) *TypedWidgetUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *TypedWidgetUpdateOne) SetNillableCount(v *int) *TypedWidgetUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *TypedWidgetUpdateOne) AddCount(v int) *TypedWidgetUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *TypedWidgetUpdateOne) SetRate(v float64) *TypedWidgetUpdateOne {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *TypedWidgetUpdateOne) SetNillableRate(v *float64) *TypedWidgetUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *TypedWidgetUpdateOne) AddRate(v float64) *TypedWidgetUpdateOne {
	_u.mutation.AddRate(v)
	return _u
}

// SetDone sets the "done" field.
func (_u *TypedWidgetUpdateOne) SetDone(v bool) *TypedWidgetUpdateOne {
	_u.mutation.SetDone(v)
	return _u
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (_u *TypedWidgetUpdateOne) SetNillableDone(v *bool) *TypedWidgetUpdateOne {
	if v != nil {
		_u.SetDone(*v)
	}
	return _u
}

// Mutation returns the TypedWidgetMutation object of the builder.
func (_u *TypedWidgetUpdateOne) Mutation() *TypedWidgetMutation {
	return _u.mutation
}

// Where appends a list predicates to the TypedWidgetUpdate builder.
func (_u *TypedWidgetUpdateOne) Where(ps ...predicate.TypedWidget) *TypedWidgetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TypedWidgetUpdateOne) Select(field string, fields ...string) *TypedWidgetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TypedWidget entity.
func (_u *TypedWidgetUpdateOne) Save(ctx context.Context) (*TypedWidget, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TypedWidgetUpdateOne) SaveX(ctx context.Context) *TypedWidget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TypedWidgetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TypedWidgetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TypedWidgetUpdateOne) sqlSave(ctx context.Context) (_node *TypedWidget, err error) {
	_spec := sqlgraph.NewUpdateSpec(typedwidget.Table, typedwidget.Columns, sqlgraph.NewFieldSpec(typedwidget.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TypedWidget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, typedwidget.FieldID)
		for _, f := range fields {
			if !typedwidget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != typedwidget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(typedwidget.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(typedwidget.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(typedwidget.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(typedwidget.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(typedwidget.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Done(); ok {
		_spec.SetField(typedwidget.FieldDone, field.TypeBool, value)
	}
	_node = &TypedWidget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{typedwidget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
