// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/polagonow/pola/repository/ent/enttest/ent/typedwidget"
)

// TypedWidget is the model entity for the TypedWidget schema.
type TypedWidget struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate float64 `json:"rate,omitempty"`
	// Done holds the value of the "done" field.
	Done         bool `json:"done,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TypedWidget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case typedwidget.FieldDone:
			values[i] = new(sql.NullBool)
		case typedwidget.FieldRate:
			values[i] = new(sql.NullFloat64)
		case typedwidget.FieldID, typedwidget.FieldCount:
			values[i] = new(sql.NullInt64)
		case typedwidget.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TypedWidget fields.
func (_m *TypedWidget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case typedwidget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case typedwidget.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case typedwidget.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case typedwidget.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.Float64
			}
		case typedwidget.FieldDone:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field done", values[i])
			} else if value.Valid {
				_m.Done = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TypedWidget.
// This includes values selected through modifiers, order, etc.
func (_m *TypedWidget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TypedWidget.
// Note that you need to call TypedWidget.Unwrap() before calling this method if this TypedWidget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TypedWidget) Update() *TypedWidgetUpdateOne {
	return NewTypedWidgetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TypedWidget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TypedWidget) Unwrap() *TypedWidget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TypedWidget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TypedWidget) String() string {
	var builder strings.Builder
	builder.WriteString("TypedWidget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("done=")
	builder.WriteString(fmt.Sprintf("%v", _m.Done))
	builder.WriteByte(')')
	return builder.String()
}

// TypedWidgets is a parsable slice of TypedWidget.
type TypedWidgets []*TypedWidget
