// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polagonow/pola/repository/ent/enttest/ent/typedwidget"
)

// TypedWidgetCreate is the builder for creating a TypedWidget entity.
type TypedWidgetCreate struct {
	config
	mutation *TypedWidgetMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *TypedWidgetCreate) SetTitle(v string) *TypedWidgetCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *TypedWidgetCreate) SetCount(v int) *TypedWidgetCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *TypedWidgetCreate) SetRate(v float64) *TypedWidgetCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetDone sets the "done" field.
func (_c *TypedWidgetCreate) SetDone(v bool) *TypedWidgetCreate {
	_c.mutation.SetDone(v)
	return _c
}

// Mutation returns the TypedWidgetMutation object of the builder.
func (_c *TypedWidgetCreate) Mutation() *TypedWidgetMutation {
	return _c.mutation
}

// Save creates the TypedWidget in the database.
func (_c *TypedWidgetCreate) Save(ctx context.Context) (*TypedWidget, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TypedWidgetCreate) SaveX(ctx context.Context) *TypedWidget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TypedWidgetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TypedWidgetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TypedWidgetCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "TypedWidget.title"`)}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "TypedWidget.count"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "TypedWidget.rate"`)}
	}
	if _, ok := _c.mutation.Done(); !ok {
		return &ValidationError{Name: "done", err: errors.New(`ent: missing required field "TypedWidget.done"`)}
	}
	return nil
}

func (_c *TypedWidgetCreate) sqlSave(ctx context.Context) (*TypedWidget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TypedWidgetCreate) createSpec() (*TypedWidget, *sqlgraph.CreateSpec) {
	var (
		_node = &TypedWidget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(typedwidget.Table, sqlgraph.NewFieldSpec(typedwidget.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(typedwidget.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(typedwidget.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(typedwidget.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.Done(); ok {
		_spec.SetField(typedwidget.FieldDone, field.TypeBool, value)
		_node.Done = value
	}
	return _node, _spec
}

// TypedWidgetCreateBulk is the builder for creating many TypedWidget entities in bulk.
type TypedWidgetCreateBulk struct {
	config
	err      error
	builders []*TypedWidgetCreate
}

// Save creates the TypedWidget entities in the database.
func (_c *TypedWidgetCreateBulk) Save(ctx context.Context) ([]*TypedWidget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TypedWidget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TypedWidgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TypedWidgetCreateBulk) SaveX(ctx context.Context) []*TypedWidget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TypedWidgetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TypedWidgetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
