// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polagonow/pola/repository/ent/enttest/ent/predicate"
	"github.com/polagonow/pola/repository/ent/enttest/ent/typedwidget"
)

// TypedWidgetDelete is the builder for deleting a TypedWidget entity.
type TypedWidgetDelete struct {
	config
	hooks    []Hook
	mutation *TypedWidgetMutation
}

// Where appends a list predicates to the TypedWidgetDelete builder.
func (_d *TypedWidgetDelete) Where(ps ...predicate.TypedWidget) *TypedWidgetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TypedWidgetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TypedWidgetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TypedWidgetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(typedwidget.Table, sqlgraph.NewFieldSpec(typedwidget.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TypedWidgetDeleteOne is the builder for deleting a single TypedWidget entity.
type TypedWidgetDeleteOne struct {
	_d *TypedWidgetDelete
}

// Where appends a list predicates to the TypedWidgetDelete builder.
func (_d *TypedWidgetDeleteOne) Where(ps ...predicate.TypedWidget) *TypedWidgetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TypedWidgetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{typedwidget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TypedWidgetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
