// The content source. `@pola/fumadocs/source` is a virtual module generated by
// Pola's Go build: it walks `web/content/docs/**`, compiles each `.mdx` with the
// Go-native pipeline, and reads `meta.json` folder configs — the Node-free
// replacement for `fumadocs-mdx`. We feed it to the real fumadocs-core loader().
import { loader } from "fumadocs-core/source";
import { source as docsSource } from "@pola/fumadocs/source";

export const source = loader({
  baseUrl: "/docs",
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  source: docsSource as any,
});
