package mdx

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// sourceEntry is one discovered content file.
type sourceEntry struct {
	kind    string // "page" or "meta"
	relPath string // POSIX path relative to the content root (e.g. "guides/intro.mdx")
	absPath string // absolute path on disk
}

// GenerateSourceModule walks contentDir for Markdown/MDX pages and `meta.json`
// folder configs and returns TypeScript for a module exporting
//
//	export const source = { files: [ {type:'page'|'meta', path, data}, ... ] }
//
// shaped for fumadocs-core/source's loader(). Each page is imported from its
// compiled module (via the .mdx esbuild loader), so `data` carries the body
// component plus toc/structuredData and the frontmatter fields (title, ...).
//
// This is the Node-free replacement for fumadocs-mdx's `.source` generation: the
// walk runs in Go during the esbuild build, emitting a virtual module.
func GenerateSourceModule(contentDir string) (string, error) {
	entries, err := walkContent(contentDir)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("// Code generated by pola (renderer/mdx). DO NOT EDIT.\n")

	// Import every page module up front with a stable alias.
	alias := make(map[string]string, len(entries))
	pageN := 0
	for _, e := range entries {
		if e.kind != "page" {
			continue
		}
		a := fmt.Sprintf("doc%d", pageN)
		alias[e.relPath] = a
		fmt.Fprintf(&b, "import * as %s from %q;\n", a, filepath.ToSlash(e.absPath))
		pageN++
	}

	b.WriteString("export const source = { files: [\n")
	for _, e := range entries {
		switch e.kind {
		case "page":
			a := alias[e.relPath]
			// data = { title:"Untitled", ...frontmatter, body, toc, structuredData }.
			// The frontmatter spread lets title/description/etc. override the default.
			fmt.Fprintf(&b,
				"  { type: \"page\", path: %q, data: { title: \"Untitled\", ...%s.frontmatter, body: %s.default, toc: %s.toc, structuredData: %s.structuredData } },\n",
				e.relPath, a, a, a, a)
		case "meta":
			data, rerr := os.ReadFile(e.absPath)
			if rerr != nil {
				continue
			}
			var tmp any
			if json.Unmarshal(data, &tmp) != nil {
				continue // skip malformed meta.json rather than break the build
			}
			fmt.Fprintf(&b, "  { type: \"meta\", path: %q, data: %s },\n", e.relPath, strings.TrimSpace(string(data)))
		}
	}
	b.WriteString("] };\n")
	return b.String(), nil
}

// walkContent recursively collects page and meta files under contentDir. Missing
// directories yield an empty list (a non-docs app that never adds content still
// builds). Results are sorted by relative path for deterministic output.
func walkContent(contentDir string) ([]sourceEntry, error) {
	info, err := os.Stat(contentDir)
	if err != nil || !info.IsDir() {
		return nil, nil
	}
	var entries []sourceEntry
	walkErr := filepath.WalkDir(contentDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, rerr := filepath.Rel(contentDir, path)
		if rerr != nil {
			return rerr
		}
		rel = filepath.ToSlash(rel)
		switch {
		case strings.HasSuffix(path, ".mdx"), strings.HasSuffix(path, ".md"):
			entries = append(entries, sourceEntry{kind: "page", relPath: rel, absPath: path})
		case filepath.Base(path) == "meta.json":
			entries = append(entries, sourceEntry{kind: "meta", relPath: rel, absPath: path})
		}
		return nil
	})
	if walkErr != nil {
		return nil, fmt.Errorf("mdx: walk content dir %q: %w", contentDir, walkErr)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].relPath < entries[j].relPath })
	return entries, nil
}
