// Code generated by ent, DO NOT EDIT.

package typedwidget

import (
	"entgo.io/ent/dialect/sql"
	"github.com/polagonow/pola/repository/ent/enttest/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldTitle, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldCount, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldRate, v))
}

// Done applies equality check predicate on the "done" field. It's identical to DoneEQ.
func Done(v bool) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldDone, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldContainsFold(FieldTitle, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLTE(FieldCount, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v float64) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldLTE(FieldRate, v))
}

// DoneEQ applies the EQ predicate on the "done" field.
func DoneEQ(v bool) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldEQ(FieldDone, v))
}

// DoneNEQ applies the NEQ predicate on the "done" field.
func DoneNEQ(v bool) predicate.TypedWidget {
	return predicate.TypedWidget(sql.FieldNEQ(FieldDone, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TypedWidget) predicate.TypedWidget {
	return predicate.TypedWidget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TypedWidget) predicate.TypedWidget {
	return predicate.TypedWidget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TypedWidget) predicate.TypedWidget {
	return predicate.TypedWidget(sql.NotPredicates(p))
}
