// Package beego implements the Beego ORM migration diff generator. The canonical
// db/models structs are ORM-neutral (no beego tags), so this generator parses
// them back into ModelDefinitions and synthesizes ephemeral beego-tagged mirror
// structs for the Atlas provider. The temp module selects beego's acronym-aware
// naming (matching the runtime adapter) so columns line up (ID → id).
package beego

import (
	"context"
	"embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/polagonow/pola/internal/generators/migration/diff"
	"github.com/polagonow/pola/internal/generators/model/schema"
)

//go:embed all:_templates
var templates embed.FS

var diffTmpl = template.Must(
	template.New("beego_diff_main.go.tmpl").Delims("[[", "]]").ParseFS(templates, "_templates/beego_diff_main.go.tmpl"),
)

// BeegoDiffGenerator generates migrations by diffing beego-tagged mirror structs
// synthesized from the neutral canonical models.
type BeegoDiffGenerator struct{}

func (g *BeegoDiffGenerator) Name() string { return "beego" }

func (g *BeegoDiffGenerator) Diff(ctx context.Context, cfg diff.Config) error {
	modelsDir := filepath.Join(cfg.ProjectDir, cfg.ModelsDir)
	defs, err := schema.ParseModelsDir(modelsDir)
	if err != nil {
		return fmt.Errorf("parse models in %s: %w", modelsDir, err)
	}
	if len(defs) == 0 {
		return fmt.Errorf("no models found in %s", modelsDir)
	}

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	imports := map[string]bool{}
	var structs strings.Builder
	for _, name := range names {
		src, imps := mirrorStruct(defs[name])
		structs.WriteString(src)
		structs.WriteString("\n")
		for imp := range imps {
			imports[imp] = true
		}
	}

	tmpDir, err := os.MkdirTemp("", "pola-beego-diff-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	if err := os.WriteFile(filepath.Join(tmpDir, "models_gen.go"), []byte(renderModelsGen(imports, structs.String())), 0o644); err != nil {
		return fmt.Errorf("write models_gen.go: %w", err)
	}

	// Generate main.go from template.
	data := struct {
		ModulePath   string
		ModelsDir    string
		DriverImport string
		AtlasDialect string
		BeegoDialect string
		Models       []string
	}{
		ModulePath:   cfg.ModulePath,
		ModelsDir:    cfg.ModelsDir,
		DriverImport: diff.DriverImportForAdapter(cfg.Adapter),
		AtlasDialect: diff.AtlasDialectForAdapter(cfg.Adapter),
		BeegoDialect: beegoDialectForAdapter(cfg.Adapter),
		Models:       names,
	}

	var buf strings.Builder
	if err := diffTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute beego diff template: %w", err)
	}

	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}

	if err := diff.WriteGoMod(tmpDir, "pola-beego-diff", cfg); err != nil {
		return err
	}

	tidy := exec.CommandContext(ctx, "go", "mod", "tidy")
	tidy.Dir = tmpDir
	if out, err := tidy.CombinedOutput(); err != nil {
		return fmt.Errorf("go mod tidy: %s\n%w", out, err)
	}

	run := exec.CommandContext(ctx, "go", "run", ".", cfg.MigrationsDir, cfg.Name)
	run.Dir = tmpDir
	run.Stdout = os.Stdout
	run.Stderr = os.Stderr
	if err := run.Run(); err != nil {
		return fmt.Errorf("beego migration diff: %w", err)
	}

	return nil
}

// renderModelsGen assembles models_gen.go: package clause, stdlib imports, and
// the synthesized beego-tagged mirror structs.
func renderModelsGen(imports map[string]bool, structs string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pola migration diff; DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	if len(imports) > 0 {
		imps := make([]string, 0, len(imports))
		for i := range imports {
			imps = append(imps, i)
		}
		sort.Strings(imps)
		b.WriteString("import (\n")
		for _, i := range imps {
			b.WriteString("\t" + i + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(structs)
	return b.String()
}

// mirrorStruct renders a beego-tagged struct reproducing def's table. Column
// names come from beego's acronym-aware strategy (set in main.go), so the mirror
// fields carry no column() tag — only auto/pk, null, size and type attributes.
func mirrorStruct(def *schema.ModelDefinition) (string, map[string]bool) {
	imports := map[string]bool{}
	var b strings.Builder

	fmt.Fprintf(&b, "type %s struct {\n", def.Name)
	if def.HasUUIDPrimaryKey() {
		b.WriteString("\tID string `orm:\"pk;size(36)\"`\n")
	} else {
		// uint ID is auto-detected as the auto-increment pk by beego.
		b.WriteString("\tID uint\n")
	}

	for _, f := range def.Fields {
		if f.Type == schema.FieldReferences {
			goType := "uint"
			if f.RefIDType == schema.FieldUUID {
				goType = "string"
			}
			fmt.Fprintf(&b, "\t%sID %s%s\n", schema.PascalCase(f.Name), goType, beegoTag(nil, f.Optional))
			if f.Polymorphic {
				fmt.Fprintf(&b, "\t%sType string%s\n", schema.PascalCase(f.Name), beegoTag([]string{"size(255)"}, f.Optional))
			}
			continue
		}
		fmt.Fprintf(&b, "\t%s %s%s\n", schema.PascalCase(f.Name), mirrorGoType(f, imports), beegoScalarTag(f))
	}

	if def.HasTimestamps {
		imports[`"time"`] = true
		b.WriteString("\tCreatedAt time.Time\n\tUpdatedAt time.Time\n")
	}
	if def.SoftDeletes {
		imports[`"time"`] = true
		b.WriteString("\tDeletedAt *time.Time `orm:\"null\"`\n")
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "\nfunc (%s) TableName() string { return %q }\n", def.Name, schema.SnakeCase(schema.Pluralize(def.Name)))
	return b.String(), imports
}

// mirrorGoType returns the Go type used in the beego mirror struct. uuid and
// json are represented as strings so the mirror needs no external deps.
func mirrorGoType(f schema.Field, imports map[string]bool) string {
	switch {
	case f.Type == schema.FieldUUID, f.Type == schema.FieldString, f.Type == schema.FieldText,
		f.Type == schema.FieldJSON, schema.ValidatorFieldTypes[f.Type]:
		return "string"
	case f.Type == schema.FieldInt:
		return "int"
	case f.Type == schema.FieldInt64:
		return "int64"
	case f.Type == schema.FieldFloat:
		return "float64"
	case f.Type == schema.FieldBool:
		return "bool"
	case f.Type == schema.FieldTime:
		imports[`"time"`] = true
		return "time.Time"
	case f.Type == schema.FieldBytes:
		return "[]byte"
	default:
		return "string"
	}
}

// beegoScalarTag builds the orm tag for a scalar column (size/type + null).
func beegoScalarTag(f schema.Field) string {
	var parts []string
	switch {
	case f.Type == schema.FieldUUID:
		parts = append(parts, "size(36)")
	case f.Type == schema.FieldString || schema.ValidatorFieldTypes[f.Type]:
		if f.Limit > 0 {
			parts = append(parts, fmt.Sprintf("size(%d)", f.Limit))
		} else {
			parts = append(parts, "size(255)")
		}
	case f.Type == schema.FieldText:
		parts = append(parts, "type(text)")
	case f.Type == schema.FieldJSON:
		parts = append(parts, "type(json)")
	case f.Type == schema.FieldBytes:
		if f.Limit > 0 {
			parts = append(parts, fmt.Sprintf("size(%d)", f.Limit))
		}
	}
	return beegoTag(parts, f.Optional)
}

// beegoTag joins orm attribute parts (adding null when optional) into a struct
// tag, or returns "" when there is nothing to emit.
func beegoTag(parts []string, optional bool) string {
	if optional {
		parts = append(parts, "null")
	}
	if len(parts) == 0 {
		return ""
	}
	return " `orm:\"" + strings.Join(parts, ";") + "\"`"
}

// beegoDialectForAdapter returns the Beego ORM driver name for the given adapter.
func beegoDialectForAdapter(adapter string) string {
	switch adapter {
	case "sqlite":
		return "sqlite3"
	case "postgresql":
		return "postgres"
	case "mysql":
		return "mysql"
	default:
		return "postgres"
	}
}
