package mcp

import (
	"context"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/polagonow/pola/core"
)

// Plugin returns a Pola plugin that exposes an MCP server. Apply options
// to customize transport, mount path, server identity, and middleware.
//
// The plugin:
//   - Builds an *mcp.Server during Register, applies all package-level
//     init()-time registrations, and provides the server in the DI
//     container so user plugins can resolve it via
//     core.MustInvoke[*mcp.Server] and add more tools dynamically.
//   - For TransportHTTP / TransportSSE: registers a core.Middleware that
//     short-circuits requests under the mount path to the SDK handler.
//   - For TransportStdio: launches an stdio-transport goroutine during
//     Start and cancels it during Shutdown.
//
// Tool/Resource/Prompt registration sources:
//  1. Package-level init() calls (RegisterTool, RegisterTypedTool, etc).
//  2. Per-file plugins generated by internal/autoload/mcp from
//     mcp/tools, mcp/resources, mcp/prompts — these run after this
//     plugin's Start and use core.Invoke to grab *mcp.Server.
//
// Place mcp.Plugin() ahead of plugins whose middleware should NOT see
// MCP requests (logging, recovery, CSRF). The pluginimports autoload
// template already does this.
func Plugin(opts ...Option) core.Plugin {
	cfg := defaultConfig()
	for _, o := range opts {
		o(cfg)
	}
	return &plugin{cfg: cfg}
}

type plugin struct {
	cfg        *config
	server     *sdk.Server
	stdioCanc  context.CancelFunc
	stdioErrCh <-chan error
}

func (p *plugin) Name() string { return "mcp" }

func (p *plugin) Register(r *core.Registry) {
	p.server = buildServer(p.cfg)
	core.ProvideValue[*sdk.Server](r, p.server)

	switch p.cfg.transport {
	case TransportHTTP, TransportSSE:
		r.AddMiddleware(&mcpMiddleware{
			mount:   p.cfg.mount,
			handler: buildHTTPHandler(p.server, p.cfg),
		})
	}
}

func (p *plugin) Start(_ context.Context) error {
	if p.cfg.transport == TransportStdio {
		cancel, errCh := runStdio(p.server)
		p.stdioCanc = cancel
		p.stdioErrCh = errCh
	}
	return nil
}

func (p *plugin) Shutdown(ctx context.Context) error {
	if p.stdioCanc != nil {
		p.stdioCanc()
		select {
		case <-p.stdioErrCh:
		case <-ctx.Done():
		}
	}
	return nil
}
