// Package build compiles the GoJSX app using esbuild.
//
// # Architecture
//
// Two esbuild passes produce one JS bundle for the Goja server VM and one
// ESM bundle for the browser:
//
//  1. Pages pass  (server conditions, CJS)
//     Entry: pre-generated by ServerEntryGenerator (passed as ServerEntryContent)
//     Output: framework-specific wire format (e.g. RSC Flight)
//
//  2. Client pass (browser condition, ESM)
//     Entry: app/_client.tsx + "use client" components
//     Bundles: React + react-dom/client + react-server-dom-esm/client
//     Output: ESM files written to public/
//
// Final Goja VM bundle = pages CJS bundle (polyfills are native Go in runtime/polyfill)
package bundler

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

// BundleResult is the output of a successful build.
type BundleResult struct {
	// ServerBundlePath is the on-disk path of the emitted server CJS bundle.
	ServerBundlePath string

	// ServerBundle is the compiled server CJS bundle in memory.
	// Populated alongside ServerBundlePath so callers can skip os.ReadFile.
	ServerBundle []byte

	// ClientFiles maps relative output path → bytes written to OutDir.
	ClientFiles map[string][]byte

	// ClientEntryOutput is the /public/... URL of the compiled client
	// injected as <script type="module" src="..."> in the HTML shell.
	ClientEntryOutput string

	// Manifest is the JSON client component manifest passed to __CLIENT_MANIFEST__
	// in the server bundle. Format: {moduleId: {id, chunks, name, async}}.
	// chunks is set to ["default"] so that react-server-dom-esm/client reads
	// metadata[1] as the export name ("default") rather than a chunk URL.
	Manifest []byte

	// ImportURLs maps module IDs to their browser-loadable chunk URLs.
	// Used by the HTML shell's <script type="importmap"> so that
	// import("components/Counter") resolves to /public/Counter-HASH.js.
	ImportURLs map[string]string
}

// BundlerConfig controls both build passes.
type BundlerConfig struct {
	// AppDir is the root of the app/ directory (absolute or relative to cwd).
	AppDir string

	// OutDir is where client bundles are written (e.g. "./public").
	OutDir string

	// ClientEntry is app/_client.tsx — the browser bootstrap.
	ClientEntry string

	// ServerEntry is the path where the server CJS bundle is emitted.
	// Defaults to filepath.Dir(OutDir)/_server.js when empty.
	ServerEntry string

	// ClientComponents are all "use client" TSX files.
	ClientComponents []string

	// External packages to mark external in all builds.
	External []string

	// AssetsURLPath is the URL prefix for client bundle files served by the
	// static file handler (e.g. "/public/assets"). No trailing slash.
	// Defaults to "/public/assets" when empty.
	AssetsURLPath string

	// Dev enables development mode: real error messages are preserved in the
	// RSC Flight stream and bundles are not minified.
	Dev bool

	// ServerEntryContent is the pre-generated server entry TypeScript source
	// produced by ServerEntryGenerator.Generate.
	ServerEntryContent string

	// ServerBundleConditions are the esbuild conditions for the server pass.
	ServerBundleConditions []string

	// ServerBundleDefines are additional esbuild defines merged into the server
	// pass (e.g. {"__DEV__": "true"}). __CLIENT_MANIFEST__ is always injected
	// from the manifest produced by the client pass.
	ServerBundleDefines map[string]string
}

// Bundle runs both esbuild passes and returns the combined result.
// ServerEntryContent must be pre-generated by the caller (e.g. via
// ReactRSCEntryGenerator.Generate) and passed in cfg.
func Bundle(cfg BundlerConfig) (*BundleResult, error) {
	if err := os.MkdirAll(cfg.OutDir, 0o755); err != nil {
		return nil, fmt.Errorf("bundler: mkdir %s: %w", cfg.OutDir, err)
	}

	absDir, err := filepath.Abs(".")
	if err != nil {
		return nil, fmt.Errorf("bundler: abs cwd: %w", err)
	}

	// ------------------------------------------------------------------ //
	// Probe — auto-discover "use client" files from the server entry     //
	// Handles framework packages (@gojsx/react-renderer) and any        //
	// third-party library with a "use client" directive automatically.   //
	// ------------------------------------------------------------------ //
	if probed := probeServerEntryClientFiles(cfg, absDir); len(probed) > 0 {
		seen := make(map[string]bool, len(cfg.ClientComponents))
		for _, c := range cfg.ClientComponents {
			abs, _ := filepath.Abs(c)
			seen[abs] = true
		}
		for _, p := range probed {
			if !seen[p] {
				cfg.ClientComponents = append(cfg.ClientComponents, p)
				seen[p] = true
			}
		}
	}

	// ------------------------------------------------------------------ //
	// Pass 1 — Client bundle (browser ESM)                                //
	// Build first so we know output filenames before building the manifest //
	// ------------------------------------------------------------------ //
	clientFiles, clientEntryOutput, metafile, err := buildClientBundle(cfg, absDir)
	if err != nil {
		return nil, err
	}

	absOutDir, err := filepath.Abs(cfg.OutDir)
	if err != nil {
		return nil, fmt.Errorf("bundler: abs outdir: %w", err)
	}
	inputChunkURLs := BuildInputChunkURLs(metafile, absDir, absOutDir, cfg.AssetsURLPath)

	manifest, importURLs, err := BuildManifest(cfg.ClientComponents, clientFiles, cfg.AppDir, cfg.AssetsURLPath, inputChunkURLs)
	if err != nil {
		return nil, fmt.Errorf("bundler: manifest: %w", err)
	}
	manifestJSON, _ := json.MarshalIndent(manifest, "", "  ")
	_ = os.WriteFile(filepath.Join(cfg.OutDir, "manifest.json"), manifestJSON, 0o644)

	// ------------------------------------------------------------------ //
	// Pass 2 — Pages bundle (react-server condition, CJS)                 //
	// Includes react-server-dom-webpack/server.browser which produces     //
	// RSC Flight wire format from renderToReadableStream().               //
	// __webpack_require__ is stubbed in polyfills.js.                     //
	// ------------------------------------------------------------------ //
	manifestDefine, err := json.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("bundler: manifest pass: %w", err)
	}

	serverEntry := cfg.ServerEntry
	if serverEntry == "" {
		serverEntry = filepath.Join(filepath.Dir(absOutDir), "_server.js")
	} else {
		serverEntry, err = filepath.Abs(serverEntry)
		if err != nil {
			return nil, fmt.Errorf("bundler: abs server entry: %w", err)
		}
	}

	serverBundlePath, err := buildPagesBundle(cfg, absDir, string(manifestDefine), serverEntry)
	if err != nil {
		return nil, fmt.Errorf("bundler: pages pass: %w", err)
	}

	serverBundle, err := os.ReadFile(serverBundlePath)
	if err != nil {
		return nil, fmt.Errorf("bundler: read server bundle: %w", err)
	}

	return &BundleResult{
		ServerBundlePath:  serverBundlePath,
		ServerBundle:      serverBundle,
		ClientFiles:       clientFiles,
		ClientEntryOutput: clientEntryOutput,
		Manifest:          manifestJSON,
		ImportURLs:        importURLs,
	}, nil
}

// buildPagesBundle generates a server entry from cfg.Pages and compiles it
// with the react-server condition using esbuild's Stdin option — no
// hand-maintained server-entry.tsx file needed.
//
// "use client" files are intercepted by the useClientPlugin: instead of being
// bundled or marked external, each one is replaced with a synthetic module that
// calls createClientModuleProxy(moduleId). This is the standard RSC bundler
// pattern (used by Next.js, Parcel, etc.) — the server never runs client code,
// it only emits a ClientReference that the Flight encoder serialises as an
// I: row. The browser receives that row, imports the real chunk, and renders
// the component with full React state.
// newAtAliasPlugin returns an esbuild plugin that resolves @/ imports to absAppDir.
// e.g. import foo from "@/jsi"  →  absAppDir/jsi
//
// We delegate back to build.Resolve so esbuild handles extension lookup,
// directory index files, etc. rather than returning a bare path ourselves.
func newAtAliasPlugin(absAppDir string) api.Plugin {
	return api.Plugin{
		Name: "at-alias",
		Setup: func(build api.PluginBuild) {
			build.OnResolve(api.OnResolveOptions{Filter: `^@/`}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
				// "@/foo/bar" → "./foo/bar" resolved from the app root
				rel := "." + args.Path[1:]
				result := build.Resolve(rel, api.ResolveOptions{
					ResolveDir: absAppDir,
					Kind:       args.Kind,
				})
				if len(result.Errors) > 0 {
					return api.OnResolveResult{}, fmt.Errorf("%s", result.Errors[0].Text)
				}
				return api.OnResolveResult{Path: result.Path}, nil
			})
		},
	}
}

func buildPagesBundle(cfg BundlerConfig, absDir string, manifestDefineJSON string, serverOutFile string) (string, error) {
	if cfg.ServerEntryContent == "" {
		return "", nil
	}
	if len(cfg.ServerBundleConditions) == 0 {
		return "", fmt.Errorf("bundler: ServerBundleConditions must not be empty")
	}

	entryStr := cfg.ServerEntryContent
	absAppDir, _ := filepath.Abs(cfg.AppDir)

	// Build a set of absolute paths for quick lookup inside the plugin.
	clientSet := make(map[string]string) // absPath → moduleId
	for _, src := range cfg.ClientComponents {
		abs, err := filepath.Abs(src)
		if err != nil {
			abs = src
		}
		clientSet[abs] = computeModuleID(absAppDir, abs)
	}

	// useClientPlugin intercepts "use client" files during the server pass and
	// replaces them with a synthetic proxy stub.
	//
	// Why OnLoad (not OnResolve): TypeScript imports omit file extensions
	// (e.g. `import Counter from "./Counter"`). OnResolve sees the raw import
	// specifier before extension resolution, so a filter like `\.(tsx|ts)$`
	// would never match. OnLoad fires after esbuild has fully resolved the path
	// (args.Path is always the absolute path with extension), so the filter works
	// correctly and we can read the real file to detect the directive.
	useClientPlugin := api.Plugin{
		Name: "resolve-client-imports",
		Setup: func(build api.PluginBuild) {
			build.OnLoad(api.OnLoadOptions{Filter: `\.(tsx|ts|jsx|js)$`}, func(args api.OnLoadArgs) (api.OnLoadResult, error) {
				// Read the file to check for the 'use client' directive,
				// mirroring how the JS plugin calls readFile on each resolved import.
				contents, err := os.ReadFile(args.Path)
				if err != nil {
					return api.OnLoadResult{}, nil
				}
				// A file is a client component if it is explicitly registered in
				// clientSet OR if its content begins with the "use client" directive.
				// Checking clientSet first handles files whose directive is preceded
				// by comments (e.g. global-error.tsx).
				_, inClientSet := clientSet[args.Path]
				trimmed := strings.TrimSpace(string(contents))
				hasDirective := strings.HasPrefix(trimmed, "'use client'") || strings.HasPrefix(trimmed, `"use client"`)
				if !inClientSet && !hasDirective {
					// Not a client component — let esbuild handle normally.
					return api.OnLoadResult{}, nil
				}

				// Compute moduleId: prefer the pre-registered value from clientSet
				// (guarantees manifest alignment), fall back to computeModuleID.
				moduleId, ok := clientSet[args.Path]
				if !ok {
					moduleId = computeModuleID(absAppDir, args.Path)
				}

				// Emit the synthetic server-side stub:
				//   import { createClientModuleProxy } from "react-server-dom-webpack/server.browser";
				//   module.exports = createClientModuleProxy("<moduleId>");
				// The proxy intercepts any property access and returns a registered
				// ClientReference, which the Flight encoder serialises as an I: row.
				stub := fmt.Sprintf(
					`import { createClientModuleProxy } from "react-server-dom-webpack/server.browser";`+"\n"+
						`module.exports = createClientModuleProxy(%q);`+"\n",
					moduleId,
				)
				return api.OnLoadResult{
					Contents:   &stub,
					Loader:     api.LoaderJS,
					ResolveDir: absAppDir,
				}, nil
			})
		},
	}

	if err := os.MkdirAll(filepath.Dir(serverOutFile), 0o755); err != nil {
		return "", fmt.Errorf("bundler: mkdir server out: %w", err)
	}

	defines := map[string]string{
		"process.env.NODE_ENV": `"production"`,
		"__DEV__":              "false",
		"__CLIENT_MANIFEST__":  manifestDefineJSON,
	}
	for k, v := range cfg.ServerBundleDefines {
		defines[k] = v
	}

	r := api.Build(api.BuildOptions{
		Stdin: &api.StdinOptions{
			Contents:   entryStr,
			ResolveDir: absAppDir, // imports resolve relative to app/
			Loader:     api.LoaderTSX,
			Sourcefile: "<generated-server-entry>",
		},
		Bundle:            true,
		Format:            api.FormatCommonJS,
		Platform:          api.PlatformBrowser,
		JSX:               api.JSXAutomatic,
		Target:            api.ES2020,
		External:          cfg.External,
		AbsWorkingDir:     absDir,
		Outfile:           serverOutFile,
		Write:             true,
		Sourcemap:         api.SourceMapNone,
		MinifyWhitespace:  true,
		MinifyIdentifiers: true,
		MinifySyntax:      true,
		Plugins:           []api.Plugin{newAtAliasPlugin(absAppDir), useClientPlugin},
		Conditions:        cfg.ServerBundleConditions,
		Define:            defines,
	})
	if len(r.Errors) > 0 {
		return "", fmtErrors("pages", r.Errors)
	}
	return serverOutFile, nil
}

// buildClientBundle compiles the browser-side entry + client components.
func buildClientBundle(cfg BundlerConfig, absDir string) (map[string][]byte, string, string, error) {
	if cfg.AssetsURLPath == "" {
		cfg.AssetsURLPath = "/public/assets"
	}
	absOutDir, err := filepath.Abs(cfg.OutDir)
	if err != nil {
		return nil, "", "", fmt.Errorf("bundler: abs outdir: %w", err)
	}
	absAppDir, _ := filepath.Abs(cfg.AppDir)

	// Build the entry points list. When ClientEntry is a package specifier
	// (e.g. "@gojsx/react-renderer/client"), generate a temporary _client.tsx
	// in absAppDir that imports it so esbuild can resolve node_modules normally
	// and the output is named _client-HASH.js as usual.
	entries := []string{}
	entryBase := ""
	if cfg.ClientEntry != "" {
		if isPackageSpecifier(cfg.ClientEntry) {
			synthPath := filepath.Join(absAppDir, "_client.tsx")
			content := fmt.Sprintf("import %q;\n", cfg.ClientEntry)
			if werr := os.WriteFile(synthPath, []byte(content), 0o644); werr == nil {
				defer os.Remove(synthPath)
				entries = append(entries, synthPath)
				entryBase = "_client"
			}
		} else {
			entries = append(entries, cfg.ClientEntry)
			entryBase = strings.TrimSuffix(filepath.Base(cfg.ClientEntry), filepath.Ext(cfg.ClientEntry))
		}
	}
	entries = append(entries, cfg.ClientComponents...)

	clientNodeEnv := `"production"`
	clientIsDev := "false"
	if cfg.Dev {
		clientNodeEnv = `"development"`
		clientIsDev = "true"
	}

	clientConditions := []string{"browser", "import", "module", "default"}

	r := api.Build(api.BuildOptions{
		EntryPoints:       entries,
		Bundle:            true,
		Format:            api.FormatESModule,
		Platform:          api.PlatformBrowser,
		JSX:               api.JSXAutomatic,
		Target:            api.ES2020,
		Splitting:         true,
		Outdir:            absOutDir,
		AbsWorkingDir:     absDir,
		Write:             false,
		Sourcemap:         api.SourceMapNone,
		MinifyWhitespace:  !cfg.Dev,
		MinifyIdentifiers: !cfg.Dev,
		MinifySyntax:      !cfg.Dev,
		EntryNames:        "[name]-[hash]",
		ChunkNames:        "chunks/[name]-[hash]",
		Conditions:        clientConditions,
		Plugins:           []api.Plugin{newAtAliasPlugin(absAppDir), newAutoDedupePlugin(absAppDir)},
		Metafile:          true,
		Define: map[string]string{
			"process.env.NODE_ENV": clientNodeEnv,
			"__DEV__":              clientIsDev,
		},
	})
	if len(r.Errors) > 0 {
		return nil, "", "", fmtErrors("client", r.Errors)
	}

	files := make(map[string][]byte)
	var entryOutput string

	for _, f := range r.OutputFiles {
		rel, _ := filepath.Rel(absOutDir, f.Path)
		if rel == "" {
			rel = filepath.Base(f.Path)
		}
		files[rel] = f.Contents
		if entryBase != "" && strings.HasPrefix(filepath.Base(rel), entryBase+"-") {
			entryOutput = cfg.AssetsURLPath + "/" + rel
		}
		_ = os.MkdirAll(filepath.Dir(f.Path), 0o755)
		_ = os.WriteFile(f.Path, f.Contents, 0o644)
	}
	return files, entryOutput, r.Metafile, nil
}

// ------------------------------------------------------------------ //
// Manifest                                                            //
// ------------------------------------------------------------------ //

// ClientManifestEntry is a single entry in the webpack-format client manifest.
type ClientManifestEntry struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Chunks []string `json:"chunks"`
	Async  bool     `json:"async"`
}

// BuildInputChunkURLs parses an esbuild metafile JSON and returns a map from
// absolute input file path → chunk URL, for every direct entry-point output.
// This allows BuildManifest to use exact mappings instead of filename heuristics,
// which fail when multiple components share the same base name (e.g. error.tsx).
func BuildInputChunkURLs(metafile, absDir, absOutDir, assetsURLPath string) map[string]string {
	if metafile == "" {
		return nil
	}
	var meta struct {
		Outputs map[string]struct {
			EntryPoint string `json:"entryPoint"`
		} `json:"outputs"`
	}
	if err := json.Unmarshal([]byte(metafile), &meta); err != nil {
		return nil
	}
	if assetsURLPath == "" {
		assetsURLPath = "/public/assets"
	}
	result := make(map[string]string)
	for outPath, info := range meta.Outputs {
		if info.EntryPoint == "" {
			continue
		}
		absOut := filepath.Join(absDir, outPath)
		relOut, err := filepath.Rel(absOutDir, absOut)
		if err != nil {
			continue
		}
		absInput := filepath.Join(absDir, info.EntryPoint)
		result[absInput] = assetsURLPath + "/" + filepath.ToSlash(relOut)
	}
	return result
}

// BuildManifest returns two things:
//
//  1. manifest — flat webpack-format map for __CLIENT_MANIFEST__ in the server
//     bundle.  react-server-dom-webpack/server emits I rows as the 3-element
//     array [id, chunks, name]. react-server-dom-esm/client reads that array
//     as [specifier, name] — so metadata[1] (chunks) is used as the export
//     name on the loaded module. Setting chunks=["default"] makes the ESM
//     client call moduleExports["default"] which is the correct export.
//
//  2. importURLs — moduleId → real chunk URL, used by the HTML import map so
//     the browser can resolve import("components/Counter") to the hashed file.
func BuildManifest(clientComponents []string, clientFiles map[string][]byte, appDir string, assetsURLPath string, inputChunkURLs map[string]string) (map[string]ClientManifestEntry, map[string]string, error) {
	if assetsURLPath == "" {
		assetsURLPath = "/public/assets"
	}
	absAppDir, _ := filepath.Abs(appDir)
	m := make(map[string]ClientManifestEntry)
	importURLs := make(map[string]string)

	for _, src := range clientComponents {
		absSrc, _ := filepath.Abs(src)
		id := computeModuleID(absAppDir, absSrc)
		base := strings.TrimSuffix(filepath.Base(src), filepath.Ext(src))

		// Find the real chunk URL for the import map.
		// Prefer the exact metafile-based mapping; fall back to filename heuristic.
		chunkURL := assetsURLPath + "/main.js"
		if url, ok := inputChunkURLs[absSrc]; ok {
			chunkURL = url
		} else {
			for out := range clientFiles {
				b := filepath.Base(out)
				if strings.HasPrefix(b, base+"-") || b == base+".js" {
					chunkURL = assetsURLPath + "/" + out
					break
				}
			}
		}
		importURLs[id] = chunkURL

		// React RSC looks up the manifest using "moduleId#exportName".
		// The proxy stub is CJS (module.exports = createClientModuleProxy(id)),
		// so React encodes an empty export name → key = id + "#".
		// We also register id + "#default" for any ESM default-import paths.
		entry := ClientManifestEntry{ID: id, Name: "default", Chunks: []string{"default"}}
		m[id+"#"] = entry
		m[id+"#default"] = entry
	}
	return m, importURLs, nil
}

// isPackageSpecifier reports whether s is a Node package specifier rather than
// a file path. Package specifiers don't start with ".", "/" or a drive letter.
func isPackageSpecifier(s string) bool {
	return s != "" && !filepath.IsAbs(s) && !strings.HasPrefix(s, ".") && !strings.HasPrefix(s, "/")
}

// computeModuleID returns a stable module ID for a client component file.
// Files inside node_modules get a package-path id (e.g. "@gojsx/react-renderer/components/ErrorBoundary").
// App files get a relative path id (e.g. "components/ThemeToggle").
func computeModuleID(absAppDir, absPath string) string {
	if idx := strings.LastIndex(absPath, "/node_modules/"); idx != -1 {
		id := absPath[idx+len("/node_modules/"):]
		return filepath.ToSlash(strings.TrimSuffix(id, filepath.Ext(id)))
	}
	rel, err := filepath.Rel(absAppDir, absPath)
	if err != nil {
		return filepath.Base(absPath)
	}
	return strings.ReplaceAll(strings.TrimSuffix(rel, filepath.Ext(rel)), string(filepath.Separator), "/")
}

// probeServerEntryClientFiles runs the server entry through esbuild with Write:false
// and an OnLoad plugin that intercepts any "use client" file, records its absolute
// path, and returns an empty stub so esbuild does not recurse into it.
// This auto-discovers all framework and third-party "use client" files without
// any manual declaration.
func probeServerEntryClientFiles(cfg BundlerConfig, absDir string) []string {
	if cfg.ServerEntryContent == "" {
		return nil
	}
	absAppDir, _ := filepath.Abs(cfg.AppDir)
	var collected []string
	probePlugin := api.Plugin{
		Name: "probe-use-client",
		Setup: func(build api.PluginBuild) {
			build.OnLoad(api.OnLoadOptions{Filter: `\.(tsx|ts|jsx|js)$`}, func(args api.OnLoadArgs) (api.OnLoadResult, error) {
				contents, err := os.ReadFile(args.Path)
				if err != nil {
					return api.OnLoadResult{}, nil
				}
				trimmed := strings.TrimSpace(string(contents))
				if !strings.HasPrefix(trimmed, `"use client"`) && !strings.HasPrefix(trimmed, `'use client'`) {
					return api.OnLoadResult{}, nil
				}
				collected = append(collected, args.Path)
				empty := ""
				return api.OnLoadResult{Contents: &empty, Loader: api.LoaderJS}, nil
			})
		},
	}
	defines := map[string]string{
		"process.env.NODE_ENV": `"production"`,
		"__DEV__":              "false",
		"__CLIENT_MANIFEST__":  "{}",
	}
	api.Build(api.BuildOptions{
		Stdin:         &api.StdinOptions{Contents: cfg.ServerEntryContent, ResolveDir: absAppDir, Loader: api.LoaderTSX, Sourcefile: "<probe>"},
		Bundle:        true,
		Write:         false,
		Outfile:       "_probe.js",
		Format:        api.FormatCommonJS,
		Platform:      api.PlatformBrowser,
		AbsWorkingDir: absDir,
		Conditions:    cfg.ServerBundleConditions,
		External:      cfg.External,
		Define:        defines,
		Plugins:       []api.Plugin{newAtAliasPlugin(absAppDir), probePlugin},
	})
	return collected
}

// newAutoDedupePlugin returns an esbuild plugin that automatically deduplicates
// any bare package import that originates from inside a nested node_modules
// directory by re-resolving it from the app root. This prevents multiple copies
// of singleton packages (React, MobX, Zustand, etc.) when a workspace package
// accidentally lists a singleton as a regular dependency instead of a peerDependency.
//
// Only redirects when the root already has the package — never forces an
// incompatible version, so nested-only packages are left untouched.
func newAutoDedupePlugin(absAppDir string) api.Plugin {
	return api.Plugin{
		Name: "auto-dedupe",
		Setup: func(build api.PluginBuild) {
			build.OnResolve(api.OnResolveOptions{Filter: `^[^./]`}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
				// Only intercept imports from within a nested node_modules directory.
				if !strings.Contains(filepath.ToSlash(args.ResolveDir), "/node_modules/") {
					return api.OnResolveResult{}, nil
				}
				// Try resolving from the app root.
				result := build.Resolve(args.Path, api.ResolveOptions{
					ResolveDir: absAppDir,
					Kind:       args.Kind,
				})
				if len(result.Errors) == 0 && result.Path != "" {
					return api.OnResolveResult{Path: result.Path}, nil
				}
				// Root doesn't have it — let esbuild use the nested copy.
				return api.OnResolveResult{}, nil
			})
		},
	}
}

func fmtErrors(pass string, errs []api.Message) error {
	msgs := make([]string, len(errs))
	for i, e := range errs {
		if e.Location != nil {
			msgs[i] = fmt.Sprintf("%s:%d: %s", e.Location.File, e.Location.Line, e.Text)
		} else {
			msgs[i] = e.Text
		}
	}
	return fmt.Errorf("esbuild [%s]:\n%s", pass, strings.Join(msgs, "\n"))
}
