// Package storage defines the file storage interface and types for the Pola framework.
//
// Storage provides a pluggable abstraction over file storage backends.
// Built-in drivers include local filesystem (fs) and rclone (supporting 70+ cloud providers).
//
// Models can reference stored files via direct or polymorphic relationships
// using the StorageBlob and StorageAttachment models generated by `pola generate storage`.
package storage

import (
	"context"
	"errors"
	"io"
	"time"
)

// StorageDriver identifies a storage backend.
type StorageDriver string

const (
	// Filesystem is the local filesystem driver.
	Filesystem StorageDriver = "fs"
	// AmazonS3 is the rclone-based S3 driver.
	AmazonS3 StorageDriver = "s3"
)

// Storage is the storage interface.
// Implementations must be safe for concurrent use.
type Storage interface {
	// Save writes content to the given path.
	// If the path already exists, it is overwritten.
	Save(ctx context.Context, content io.Reader, path string) error

	// Stat returns metadata about the file at path.
	// Returns ErrNotExist if the file does not exist.
	Stat(ctx context.Context, path string) (*Stat, error)

	// Open returns a reader for the file at path.
	// The caller must close the returned ReadCloser.
	// Returns ErrNotExist if the file does not exist.
	Open(ctx context.Context, path string) (io.ReadCloser, error)

	// Delete removes the file at path.
	Delete(ctx context.Context, path string) error

	// List returns metadata for all files under path.
	List(ctx context.Context, path string) ([]*Stat, error)
}

// Stat contains metadata about content stored in storage.
type Stat struct {
	ModifiedTime time.Time `json:"modified_time"`
	Size         int64     `json:"size"`
	Name         string    `json:"name"`
	Path         string    `json:"path"`
	ContentType  string    `json:"content_type"`
}

// ErrNotExist is a sentinel error returned by Open and Stat
// when the requested file does not exist.
var ErrNotExist = errors.New("file does not exist")
