// Code generated by pola, then hand-edited for the SaaS starter.
package models

import (
	"time"
)

// ActivityLog is the canonical ActivityLog model: the single source of truth for
// the activity_logs table and the repository/transport entity type.
type ActivityLog struct {
	ID     uint    `pola:"pk" json:"id"`
	TeamID uint    `pola:"references:Team" json:"teamId"`
	UserID *uint   `pola:"references:User" json:"userId,omitempty"` // nullable: some events have no actor
	Action string  `pola:"type:string" json:"action" validate:"required"`
	// Timestamp / IpAddress are set server-side, not bound from the client.
	Timestamp time.Time `pola:"type:time" json:"timestamp"`
	IPAddress *string   `pola:"type:string" json:"ipAddress,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TableName pins the table name across ORMs.
func (ActivityLog) TableName() string { return "activity_logs" }
