// Code generated by pola, then hand-edited for the SaaS starter.
package models

import (
	"time"
)

// Invitation is the canonical Invitation model: the single source of truth for
// the invitations table and the repository/transport entity type.
type Invitation struct {
	ID          uint      `pola:"pk" json:"id"`
	TeamID      uint      `pola:"references:Team" json:"teamId"`
	Email       string    `pola:"type:email" json:"email" validate:"required,email"`
	InvitedByID uint      `pola:"references:User" json:"invitedById"`
	Role        string    `pola:"type:string" json:"role" validate:"required"`
	InvitedAt   time.Time `pola:"type:time" json:"invitedAt"`
	Status      string    `pola:"type:string" json:"status"` // "pending" | "accepted"
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// TableName pins the table name across ORMs.
func (Invitation) TableName() string { return "invitations" }
