// Code generated by pola, then hand-edited for the SaaS starter.
package models

import (
	"time"
)

// TeamMember is the canonical TeamMember model: the single source of truth for the
// team_members table and the repository/transport entity type.
type TeamMember struct {
	ID        uint      `pola:"pk" json:"id"`
	UserID    uint      `pola:"references:User" json:"userId"`
	TeamID    uint      `pola:"references:Team" json:"teamId"`
	Role      string    `pola:"type:string" json:"role" validate:"required"`
	JoinedAt  time.Time `pola:"type:time" json:"joinedAt"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TableName pins the table name across ORMs.
func (TeamMember) TableName() string { return "team_members" }
