// Code generated by pola, then hand-edited for the SaaS starter.
package models

import (
	"time"
)

// Team is the canonical Team model: the single source of truth for the
// teams table and the repository/transport entity type.
//
// The Stripe fields are nullable (pointers) so an un-subscribed team stores NULL
// — which keeps the UNIQUE indexes on stripe_customer_id / stripe_subscription_id
// valid across many teams (SQLite/Postgres allow multiple NULLs in a unique index).
type Team struct {
	ID                   uint       `pola:"pk" json:"id"`
	Name                 string     `pola:"type:string" json:"name" validate:"required"`
	StripeCustomerID     *string    `pola:"type:string;uniq" json:"stripeCustomerId,omitempty"`
	StripeSubscriptionID *string    `pola:"type:string;uniq" json:"stripeSubscriptionId,omitempty"`
	StripeProductID      *string    `pola:"type:string" json:"stripeProductId,omitempty"`
	PlanName             *string    `pola:"type:string" json:"planName,omitempty"`
	SubscriptionStatus   *string    `pola:"type:string" json:"subscriptionStatus,omitempty"`
	CreatedAt            time.Time  `json:"createdAt"`
	UpdatedAt            time.Time  `json:"updatedAt"`
}

// TableName pins the table name across ORMs.
func (Team) TableName() string { return "teams" }
