// Code generated by pola, then hand-edited for the SaaS starter. Fields + pola:
// tags are the source of truth for the database schema AND the
// repository/transport entity.
package models

import (
	"time"
)

// User is the canonical User model: the single source of truth for the
// users table and the repository/transport entity type.
type User struct {
	ID    uint   `pola:"pk" json:"id"`
	Name  string `pola:"type:string" json:"name"`
	Email string `pola:"type:email;uniq" json:"email" validate:"required,email"`
	// PasswordHash is never serialized to the client.
	PasswordHash string     `pola:"type:string" json:"-"`
	Role         string     `pola:"type:string" json:"role"` // "owner" | "member"; defaults to "member"
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `pola:"soft_delete" json:"deletedAt,omitempty"`
}

// TableName pins the table name across ORMs.
func (User) TableName() string { return "users" }
