// Code generated by pola. Fields + pola: tags are the source of truth for the
// database schema AND the repository/transport entity; edit them and re-run
// `pola generate model` / `pola db migrate`. This model imports no ORM package —
// ORM-specific schema is derived from the pola: tags at migration time.
package models

import (
	"time"
)

// Product is the canonical Product model: the single source of truth for the
// products table and the repository/transport entity type.
type Product struct {
	ID          uint      `pola:"pk" json:"id"`
	Name        string    `pola:"type:string" json:"name" validate:"required"`
	Price       float64   `pola:"type:float" json:"price" validate:"omitempty"`
	Description string    `pola:"type:text" json:"description" validate:"omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// TableName pins the table name across ORMs.
func (Product) TableName() string { return "products" }
