// Code generated by pola. Fields + pola: tags are the source of truth for the
// database schema AND the repository/transport entity. This model imports no
// ORM package — ORM-specific schema is derived from the pola: tags at migration
// time.
package models

// Task is the canonical Task model: the single source of truth for the tasks
// table and the repository/transport entity type.
type Task struct {
	ID    uint   `pola:"pk" json:"id"`
	Title string `pola:"type:string" json:"title" validate:"required"`
	Done  bool   `pola:"type:bool" json:"done" validate:"-"`
}

// TableName pins the table name across ORMs.
func (Task) TableName() string { return "tasks" }
