// Code generated by pola generate dto; DO NOT EDIT.
package dto

import (
	poladto "github.com/polagonow/pola/dto"
)

// Product is the response DTO returned to clients.
type Product struct {
	ID          uint    `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

// CreateProduct is the create-request DTO.
type CreateProduct struct {
	Name        string  `json:"name" validate:"required"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

// UpdateProduct is the partial-update (PATCH) DTO. Optional fields left absent
// by the client are skipped when mapped onto the model with dto.Copy.
type UpdateProduct struct {
	Name        poladto.Optional[string]  `json:"name,omitzero"`
	Price       poladto.Optional[float64] `json:"price,omitzero"`
	Description poladto.Optional[string]  `json:"description,omitzero"`
}
