// Package do provides a RuntimeInjector backed by samber/do dependency injection.
// It resolves services from a do.Injector and exposes them to the JS runtime
// as __DEPENDENCY_INJECTION__ async functions.
package do

import (
	"context"
	"fmt"

	samberdo "github.com/samber/do/v2"

	"github.com/polagonow/pola/core"
	"github.com/polagonow/pola/core/globals"
)

// Injector adapts a samber/do Injector to the RuntimeInjector interface.
type Injector struct {
	di           samberdo.Injector
	serviceFns   map[string]func(args []any) (any, error)
	capabilities []core.InjectionCapability
}

// New creates a RuntimeInjector from a do.Injector.
// Use Register to expose individual functions to the JS runtime.
func New(di samberdo.Injector) *Injector {
	return &Injector{
		di:         di,
		serviceFns: map[string]func(args []any) (any, error){},
	}
}

// Register manually registers a named function to be exposed as
// __DEPENDENCY_INJECTION__.fnName(...) in the JS runtime.
func (inj *Injector) Register(name string, fn func(args []any) (any, error)) *Injector {
	inj.serviceFns[name] = fn
	inj.capabilities = append(inj.capabilities, core.InjectionCapability{
		Name:        name,
		Description: "registered function",
	})
	return inj
}

// Ensure Injector satisfies core.RuntimeInjector.
var _ core.RuntimeInjector = (*Injector)(nil)

// Name returns the injector implementation name.
func (inj *Injector) Name() string { return "do" }

// Capabilities returns the list of functions exposed to the JS runtime.
func (inj *Injector) Capabilities() []core.InjectionCapability { return inj.capabilities }

// Inject sets the __DEPENDENCY_INJECTION__ global on the JSRuntime with all
// registered functions. Each function is available as
// __DEPENDENCY_INJECTION__.fnName(args...) in JS.
func (inj *Injector) Inject(ctx context.Context, runtime core.JSRuntime) error {
	fns := make(map[string]any, len(inj.serviceFns))
	for name, fn := range inj.serviceFns {
		captured := fn
		fns[name] = captured
	}
	return runtime.Set(globals.BridgeObject, fns)
}

// TypeScriptDeclarations generates TypeScript ambient declarations for all
// registered functions. These are consumed by the build pipeline to
// auto-generate @pola/di types.
func (inj *Injector) TypeScriptDeclarations() string {
	if len(inj.capabilities) == 0 {
		return "// No DI functions registered\n"
	}
	out := "// AUTO-GENERATED by pola — do not edit\n"
	out += fmt.Sprintf("declare const %s: {\n", globals.BridgeObject)
	for _, cap := range inj.capabilities {
		out += fmt.Sprintf("  %s: (...args: any[]) => Promise<any>\n", cap.Name)
	}
	out += "}\n"
	out += fmt.Sprintf("export default %s\n", globals.BridgeObject)
	return out
}
