// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "note", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// TypedWidgetsColumns holds the columns for the "typed_widgets" table.
	TypedWidgetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt},
		{Name: "rate", Type: field.TypeFloat64},
		{Name: "done", Type: field.TypeBool},
	}
	// TypedWidgetsTable holds the schema information for the "typed_widgets" table.
	TypedWidgetsTable = &schema.Table{
		Name:       "typed_widgets",
		Columns:    TypedWidgetsColumns,
		PrimaryKey: []*schema.Column{TypedWidgetsColumns[0]},
	}
	// WidgetsColumns holds the columns for the "widgets" table.
	WidgetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// WidgetsTable holds the schema information for the "widgets" table.
	WidgetsTable = &schema.Table{
		Name:       "widgets",
		Columns:    WidgetsColumns,
		PrimaryKey: []*schema.Column{WidgetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SessionsTable,
		TypedWidgetsTable,
		WidgetsTable,
	}
)

func init() {
}
