// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// TypedWidget is the predicate function for typedwidget builders.
type TypedWidget func(*sql.Selector)

// Widget is the predicate function for widget builders.
type Widget func(*sql.Selector)
